# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: local
    hooks:
      - id: bandit
        name: Run bandit
        language: python
        entry: bandit -c pyproject.toml -ll
        types: [file,python]

      - id: ruff
        name: Run ruff
        language: python
        entry: ruff check --force-exclude --fix
        types: [file,python]

      - id: ruff_format
        name: Run ruff format
        language: python
        entry: ruff format
        types: [file,python]
